folders = ["/home/iit.local/isorrentino/element_sensorless-torque-control/code/python/PINN_friction/results/r_ankle_roll/epochs_350_batch_4777_pastsamples_29/val_data.pickle"]

model = "/home/iit.local/isorrentino/element_sensorless-torque-control/code/python/PINN_friction/results/r_ankle_roll/epochs_350_batch_4777_pastsamples_29/model_e349.pt"
scaler = "/home/iit.local/isorrentino/element_sensorless-torque-control/code/python/PINN_friction/results/r_ankle_roll/epochs_350_batch_4777_pastsamples_29/scaler.pkl"

[joint]
joint_to_model = "r_knee"
gear_ratio = 100.0
torque_constant = 0.156977705
joint_lim_inf = -1.83567889
joint_lim_sup = 0.13519444
joint_acc_limit = 1.0
im_limit = 3.0
tauf_limit = 100.0
joint_vel_limit = 1.0