[general]
save_model = 1
save_results = 1
plot_results = 1
results_folder = 'code/python/PINN_friction/results/l_hip_yaw/'

[joint]
joint_to_model = "l_hip_yaw"
gear_ratio = -100.0
torque_constant = 0.047
joint_lim_inf = -1.42433889
joint_lim_sup = 1.4243388
joint_acc_limit = 10.0

[friction_params]
ka = 75.00514162
kv = -0.1667495
kc = 4.16443176
ks = 3.05658197
vs = -0.48184704

[data]
folders = ["code/python/datasets/ergoCubSN001/friction_datasets/current_control_experiments/senza_pesi/current_sinusoid_0_0023/l_hip_yaw/train/parsed",
        "code/python/datasets/ergoCubSN001/friction_datasets/current_control_experiments/senza_pesi/current_traj_player/train/parsed",
        "code/python/datasets/ergoCubSN001/friction_datasets/current_control_experiments/senza_pesi/ramp/l_hip_yaw/train/parsed",
        "code/python/datasets/ergoCubSN001/friction_datasets/current_control_experiments_2/l_hip_yaw/ramp/train/parsed",
        "code/python/datasets/ergoCubSN001/friction_datasets/current_control_experiments_2/l_hip_yaw/sinusoid/train/parsed",
        "code/python/datasets/ergoCubSN001/friction_datasets/current_control_experiments_2/l_hip_yaw/step/train/parsed"]
